#!/usr/bin/env bash
# deploy-test.sh — roll the `multica-test` namespace onto one image tag.
#
# This is the rollout `deploy/k8s/overlays/test/README.md` documents by hand,
# in one command, so CI and a human perform identical steps instead of two
# drifting recipes.
#
# It needs only `kubectl`. The image override goes through a throwaway overlay
# so `kubectl apply -k`'s built-in kustomize does the substitution — no
# standalone `kustomize` binary, and the committed `newTag` in
# overlays/test/kustomization.yaml is left untouched.
#
# The throwaway overlay is a SIBLING of overlays/ rather than a child of
# overlays/test/: kustomize refuses a kustomization that lists its own parent
# directory as a resource ("cycle detected: candidate root ... contains
# visited root ...").
#
# NOTE: because the committed tag is not rewritten, a later `kubectl apply -k
# deploy/k8s/overlays/test` from a laptop rolls the namespace BACK to whatever
# tag is committed. Deploy through this script (or CI) and you stay on the
# pinned tag.
#
# Usage:
#   scripts/deploy-test.sh <image-tag>
#   scripts/deploy-test.sh test-20260803-a364c09e6
#   DRY_RUN=1 scripts/deploy-test.sh <tag>   # server-side validate, change nothing

set -euo pipefail

TAG="${1:-}"
if [ -z "$TAG" ]; then
  echo "usage: scripts/deploy-test.sh <image-tag>" >&2
  exit 2
fi

NAMESPACE="${DEPLOY_NAMESPACE:-multica-test}"
REGISTRY="${DEPLOY_REGISTRY:-lilith-registry.cn-shanghai.cr.aliyuncs.com/devops}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAGE="$REPO_ROOT/deploy/k8s/.rollout"

cleanup() { rm -rf "$STAGE"; }
trap cleanup EXIT

mkdir -p "$STAGE"
cat >"$STAGE/kustomization.yaml" <<EOF
# Generated by scripts/deploy-test.sh — deleted when the script exits.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../overlays/test
images:
  - name: $REGISTRY/multica-server
    newTag: "$TAG"
  - name: $REGISTRY/multica-web
    newTag: "$TAG"
EOF

if [ -n "${DRY_RUN:-}" ]; then
  echo "▶ dry run: validating a rollout of $NAMESPACE onto $TAG"
  kubectl apply -k "$STAGE" --dry-run=server
  exit 0
fi

echo "▶ rolling $NAMESPACE onto $TAG"

# The migrate Job's pod template is immutable, so applying a new image over a
# finished Job is rejected. Delete first, then let the apply recreate it.
kubectl -n "$NAMESPACE" delete job multica-migrate --ignore-not-found
kubectl apply -k "$STAGE"

if ! kubectl -n "$NAMESPACE" wait --for=condition=complete job/multica-migrate --timeout=5m; then
  echo "❌ migrations did not complete — last 100 lines:" >&2
  kubectl -n "$NAMESPACE" logs job/multica-migrate --tail=100 >&2 || true
  exit 1
fi

kubectl -n "$NAMESPACE" rollout status deployment/multica-server --timeout=5m
kubectl -n "$NAMESPACE" rollout status deployment/multica-web --timeout=5m

echo "✅ $NAMESPACE is on $TAG"
