ALTER TABLE channel_outbound_card_message
    ADD COLUMN channel_card_id TEXT NOT NULL DEFAULT '',
    ADD COLUMN transport TEXT NOT NULL DEFAULT 'cardkit'
        CHECK (transport IN ('cardkit', 'legacy')),
    ADD COLUMN desired_revision BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN applied_revision BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN inflight_revision BIGINT,
    ADD COLUMN inflight_sequence INTEGER,
    ADD COLUMN inflight_card_json TEXT NOT NULL DEFAULT '',
    ADD COLUMN operation_sequence INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN projected_seq INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN visible_text TEXT NOT NULL DEFAULT '',
    ADD COLUMN current_stage TEXT NOT NULL DEFAULT 'processing',
    ADD COLUMN files_read_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN files_edited_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN searches_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN commands_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN terminal_content TEXT NOT NULL DEFAULT '',
    ADD COLUMN next_attempt_at TIMESTAMPTZ,
    ADD COLUMN lease_token UUID,
    ADD COLUMN lease_expires_at TIMESTAMPTZ,
    ADD COLUMN attempt_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN delivery_failed_at TIMESTAMPTZ,
    ADD COLUMN last_error TEXT NOT NULL DEFAULT '';
